CREATE TABLE IF NOT EXISTS ticket_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    ticket_category_id BIGINT NOT NULL,
    order_status VARCHAR(32) NOT NULL,
    created_time TIMESTAMP NOT NULL,
    pay_time TIMESTAMP NULL,
    cancel_time TIMESTAMP NULL,
    expire_time TIMESTAMP NOT NULL,
    CONSTRAINT uk_ticket_order_once UNIQUE (user_id, session_id, ticket_category_id)
);

CREATE TABLE IF NOT EXISTS electronic_ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    ticket_code VARCHAR(64) NOT NULL,
    ticket_status VARCHAR(32) NOT NULL,
    generated_time TIMESTAMP NOT NULL,
    verified_time TIMESTAMP NULL,
    verifier_id BIGINT NULL,
    CONSTRAINT uk_electronic_ticket_order UNIQUE (order_id),
    CONSTRAINT uk_electronic_ticket_code UNIQUE (ticket_code)
);

CREATE TABLE IF NOT EXISTS async_grab_request (
    request_id VARCHAR(64) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    ticket_category_id BIGINT NOT NULL,
    request_status VARCHAR(32) NOT NULL,
    order_id BIGINT NULL,
    error_message VARCHAR(255) NULL,
    created_time TIMESTAMP NOT NULL,
    updated_time TIMESTAMP NOT NULL
);
