CREATE TABLE IF NOT EXISTS ticket_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    ticket_category_id BIGINT NOT NULL,
    unit_price_cents BIGINT NOT NULL DEFAULT 0,
    amount_cents BIGINT NOT NULL DEFAULT 0,
    quantity INT NOT NULL DEFAULT 1,
    refunded_quantity INT NOT NULL DEFAULT 0,
    refunded_amount_cents BIGINT NOT NULL DEFAULT 0,
    passenger_name VARCHAR(64) NOT NULL DEFAULT '历史购票人',
    passenger_document_type VARCHAR(32) NOT NULL DEFAULT 'OTHER',
    passenger_document_last4 VARCHAR(4) NOT NULL DEFAULT '0000',
    active_grab_key VARCHAR(96) NULL,
    order_status VARCHAR(32) NOT NULL,
    created_time TIMESTAMP NOT NULL,
    pay_time TIMESTAMP NULL,
    cancel_time TIMESTAMP NULL,
    refund_time TIMESTAMP NULL,
    expire_time TIMESTAMP NOT NULL
);

ALTER TABLE ticket_order DROP CONSTRAINT IF EXISTS uk_ticket_order_once;
ALTER TABLE ticket_order ADD COLUMN IF NOT EXISTS unit_price_cents BIGINT NOT NULL DEFAULT 0;
ALTER TABLE ticket_order ADD COLUMN IF NOT EXISTS amount_cents BIGINT NOT NULL DEFAULT 0;
ALTER TABLE ticket_order ADD COLUMN IF NOT EXISTS quantity INT NOT NULL DEFAULT 1;
ALTER TABLE ticket_order ADD COLUMN IF NOT EXISTS refunded_quantity INT NOT NULL DEFAULT 0;
ALTER TABLE ticket_order ADD COLUMN IF NOT EXISTS refunded_amount_cents BIGINT NOT NULL DEFAULT 0;
ALTER TABLE ticket_order ADD COLUMN IF NOT EXISTS passenger_name VARCHAR(64) NOT NULL DEFAULT '历史购票人';
ALTER TABLE ticket_order ADD COLUMN IF NOT EXISTS passenger_document_type VARCHAR(32) NOT NULL DEFAULT 'OTHER';
ALTER TABLE ticket_order ADD COLUMN IF NOT EXISTS passenger_document_last4 VARCHAR(4) NOT NULL DEFAULT '0000';
ALTER TABLE ticket_order ADD COLUMN IF NOT EXISTS active_grab_key VARCHAR(96) NULL;
ALTER TABLE ticket_order ADD COLUMN IF NOT EXISTS refund_time TIMESTAMP NULL;
UPDATE ticket_order
SET active_grab_key = CONCAT(user_id, ':', session_id, ':', ticket_category_id)
WHERE order_status IN ('PENDING_PAYMENT', 'PAID', 'PARTIALLY_REFUNDED') AND active_grab_key IS NULL;
UPDATE ticket_order
SET active_grab_key = NULL
WHERE order_status IN ('CANCELED', 'REFUNDED');
ALTER TABLE ticket_order ADD CONSTRAINT IF NOT EXISTS uk_ticket_order_active UNIQUE (active_grab_key);

CREATE TABLE IF NOT EXISTS ticket_order_passenger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    passenger_sequence INT NOT NULL,
    passenger_name VARCHAR(64) NOT NULL,
    passenger_document_type VARCHAR(32) NOT NULL,
    passenger_document_last4 VARCHAR(4) NOT NULL,
    CONSTRAINT uk_ticket_order_passenger_sequence UNIQUE (order_id, passenger_sequence)
);

INSERT INTO ticket_order_passenger
    (order_id, passenger_sequence, passenger_name, passenger_document_type, passenger_document_last4)
SELECT ticket_order.id, 1, ticket_order.passenger_name,
       ticket_order.passenger_document_type, ticket_order.passenger_document_last4
FROM ticket_order
WHERE NOT EXISTS (
    SELECT 1
    FROM ticket_order_passenger
    WHERE ticket_order_passenger.order_id = ticket_order.id
);

CREATE TABLE IF NOT EXISTS electronic_ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    passenger_id BIGINT NOT NULL,
    ticket_code VARCHAR(64) NOT NULL,
    ticket_status VARCHAR(32) NOT NULL,
    generated_time TIMESTAMP NOT NULL,
    verified_time TIMESTAMP NULL,
    verifier_id BIGINT NULL,
    refunded_time TIMESTAMP NULL,
    CONSTRAINT uk_electronic_ticket_passenger UNIQUE (passenger_id),
    CONSTRAINT uk_electronic_ticket_code UNIQUE (ticket_code)
);

ALTER TABLE electronic_ticket ADD COLUMN IF NOT EXISTS passenger_id BIGINT NULL;
ALTER TABLE electronic_ticket ADD COLUMN IF NOT EXISTS refunded_time TIMESTAMP NULL;
UPDATE electronic_ticket
SET passenger_id = (
    SELECT MIN(ticket_order_passenger.id)
    FROM ticket_order_passenger
    WHERE ticket_order_passenger.order_id = electronic_ticket.order_id
)
WHERE passenger_id IS NULL;
ALTER TABLE electronic_ticket DROP CONSTRAINT IF EXISTS uk_electronic_ticket_order;
ALTER TABLE electronic_ticket ALTER COLUMN passenger_id SET NOT NULL;
ALTER TABLE electronic_ticket ADD CONSTRAINT IF NOT EXISTS uk_electronic_ticket_passenger UNIQUE (passenger_id);

CREATE TABLE IF NOT EXISTS async_grab_request (
    request_id VARCHAR(64) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    ticket_category_id BIGINT NOT NULL,
    request_status VARCHAR(32) NOT NULL,
    order_id BIGINT NULL,
    error_message VARCHAR(255) NULL,
    created_time TIMESTAMP NOT NULL,
    updated_time TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS ticket_waitlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    ticket_category_id BIGINT NOT NULL,
    unit_price_cents BIGINT NOT NULL,
    quantity INT NOT NULL,
    active_waitlist_key VARCHAR(96) NULL,
    waitlist_status VARCHAR(32) NOT NULL,
    order_id BIGINT NULL,
    created_time TIMESTAMP NOT NULL,
    updated_time TIMESTAMP NOT NULL,
    fulfilled_time TIMESTAMP NULL,
    canceled_time TIMESTAMP NULL,
    expired_time TIMESTAMP NULL,
    payment_expire_time TIMESTAMP NULL,
    CONSTRAINT uk_ticket_waitlist_active UNIQUE (active_waitlist_key)
);

CREATE TABLE IF NOT EXISTS ticket_waitlist_passenger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    waitlist_id BIGINT NOT NULL,
    passenger_sequence INT NOT NULL,
    passenger_name VARCHAR(64) NOT NULL,
    passenger_document_type VARCHAR(32) NOT NULL,
    passenger_document_last4 VARCHAR(4) NOT NULL,
    CONSTRAINT uk_ticket_waitlist_passenger_sequence UNIQUE (waitlist_id, passenger_sequence)
);

CREATE TABLE IF NOT EXISTS event_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    icon_key VARCHAR(40) NOT NULL,
    content_profile VARCHAR(32) NOT NULL DEFAULT 'GENERAL',
    display_order INT NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_time TIMESTAMP NOT NULL,
    updated_time TIMESTAMP NOT NULL,
    CONSTRAINT uk_event_category_name UNIQUE (name)
);

ALTER TABLE event_category ADD COLUMN IF NOT EXISTS content_profile VARCHAR(32) NOT NULL DEFAULT 'GENERAL';

CREATE TABLE IF NOT EXISTS event_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    location VARCHAR(160) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    poster_url VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_time TIMESTAMP NOT NULL,
    updated_time TIMESTAMP NOT NULL,
    published_time TIMESTAMP NULL
);

ALTER TABLE event_catalog ADD COLUMN IF NOT EXISTS category_id BIGINT NULL;
ALTER TABLE event_catalog ADD COLUMN IF NOT EXISTS city VARCHAR(80) NOT NULL DEFAULT '';
ALTER TABLE event_catalog ADD COLUMN IF NOT EXISTS venue_address VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE event_catalog ADD COLUMN IF NOT EXISTS duration_minutes INT NOT NULL DEFAULT 0;
ALTER TABLE event_catalog ADD COLUMN IF NOT EXISTS sale_start_time TIMESTAMP NULL;
ALTER TABLE event_catalog ADD COLUMN IF NOT EXISTS sale_end_time TIMESTAMP NULL;
ALTER TABLE event_catalog ADD COLUMN IF NOT EXISTS purchase_limit INT NOT NULL DEFAULT 1;
ALTER TABLE event_catalog ADD COLUMN IF NOT EXISTS real_name_rule VARCHAR(32) NOT NULL DEFAULT 'REQUIRED';
ALTER TABLE event_catalog ADD COLUMN IF NOT EXISTS entry_method VARCHAR(32) NOT NULL DEFAULT 'E_TICKET';
ALTER TABLE event_catalog ADD COLUMN IF NOT EXISTS refund_rule VARCHAR(1000) NOT NULL DEFAULT '';
ALTER TABLE event_catalog ADD COLUMN IF NOT EXISTS waitlist_enabled BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS event_publication (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    organizer_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    category_name VARCHAR(40) NOT NULL,
    content_profile VARCHAR(32) NOT NULL DEFAULT 'GENERAL',
    name VARCHAR(100) NOT NULL,
    city VARCHAR(80) NOT NULL,
    venue_name VARCHAR(160) NOT NULL,
    venue_address VARCHAR(255) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    poster_url VARCHAR(255) NOT NULL,
    duration_minutes INT NOT NULL,
    sale_start_time TIMESTAMP NOT NULL,
    sale_end_time TIMESTAMP NOT NULL,
    purchase_limit INT NOT NULL,
    real_name_rule VARCHAR(32) NOT NULL,
    entry_method VARCHAR(32) NOT NULL,
    refund_rule VARCHAR(1000) NOT NULL,
    waitlist_enabled BOOLEAN NOT NULL,
    published_time TIMESTAMP NOT NULL,
    CONSTRAINT uk_event_publication_event UNIQUE (event_id)
);

ALTER TABLE event_publication ADD COLUMN IF NOT EXISTS content_profile VARCHAR(32) NOT NULL DEFAULT 'GENERAL';
UPDATE event_publication
SET content_profile = COALESCE((
    SELECT category.content_profile
    FROM event_category category
    WHERE category.id = event_publication.category_id
), content_profile);

CREATE TABLE IF NOT EXISTS event_session_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS ticket_category_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    name VARCHAR(80) NOT NULL,
    price_cents BIGINT NOT NULL,
    total_stock INT NOT NULL,
    remaining_stock INT NOT NULL
);

CREATE TABLE IF NOT EXISTS event_session_publication (
    event_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    CONSTRAINT uk_event_session_publication UNIQUE (event_id, session_id)
);

CREATE TABLE IF NOT EXISTS ticket_category_publication (
    event_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    ticket_category_id BIGINT NOT NULL,
    name VARCHAR(80) NOT NULL,
    price_cents BIGINT NOT NULL,
    CONSTRAINT uk_ticket_category_publication UNIQUE (event_id, session_id, ticket_category_id)
);

CREATE TABLE IF NOT EXISTS event_rule_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    rule_group VARCHAR(32) NOT NULL,
    rule_code VARCHAR(64) NOT NULL,
    title VARCHAR(80) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    display_order INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_event_rule_catalog UNIQUE (event_id, rule_code)
);

CREATE TABLE IF NOT EXISTS event_rule_publication (
    event_id BIGINT NOT NULL,
    rule_group VARCHAR(32) NOT NULL,
    rule_code VARCHAR(64) NOT NULL,
    title VARCHAR(80) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    display_order INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_event_rule_publication UNIQUE (event_id, rule_code)
);

CREATE TABLE IF NOT EXISTS event_detail_section_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    section_type VARCHAR(32) NOT NULL,
    title VARCHAR(100) NOT NULL,
    content VARCHAR(5000) NOT NULL,
    image_url VARCHAR(255) NOT NULL DEFAULT '',
    display_order INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS event_detail_section_publication (
    event_id BIGINT NOT NULL,
    section_id BIGINT NOT NULL,
    section_type VARCHAR(32) NOT NULL,
    title VARCHAR(100) NOT NULL,
    content VARCHAR(5000) NOT NULL,
    image_url VARCHAR(255) NOT NULL DEFAULT '',
    display_order INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_event_detail_publication UNIQUE (event_id, section_id)
);

INSERT INTO event_session_publication (event_id, session_id, start_time, end_time)
SELECT session.event_id, session.id, session.start_time, session.end_time
FROM event_session_catalog session
JOIN event_publication publication ON publication.event_id = session.event_id
WHERE NOT EXISTS (
    SELECT 1 FROM event_session_publication snapshot
    WHERE snapshot.event_id = session.event_id AND snapshot.session_id = session.id
);

INSERT INTO ticket_category_publication
    (event_id, session_id, ticket_category_id, name, price_cents)
SELECT session.event_id, ticket.session_id, ticket.id, ticket.name, ticket.price_cents
FROM ticket_category_catalog ticket
JOIN event_session_catalog session ON session.id = ticket.session_id
JOIN event_publication publication ON publication.event_id = session.event_id
WHERE NOT EXISTS (
    SELECT 1 FROM ticket_category_publication snapshot
    WHERE snapshot.event_id = session.event_id
      AND snapshot.session_id = ticket.session_id
      AND snapshot.ticket_category_id = ticket.id
);

INSERT INTO event_rule_publication
    (event_id, rule_group, rule_code, title, content, display_order)
SELECT rule.event_id, rule.rule_group, rule.rule_code, rule.title, rule.content, rule.display_order
FROM event_rule_catalog rule
JOIN event_publication publication ON publication.event_id = rule.event_id
WHERE NOT EXISTS (
    SELECT 1 FROM event_rule_publication snapshot
    WHERE snapshot.event_id = rule.event_id AND snapshot.rule_code = rule.rule_code
);

INSERT INTO event_detail_section_publication
    (event_id, section_id, section_type, title, content, image_url, display_order)
SELECT section.event_id, section.id, section.section_type, section.title,
       section.content, section.image_url, section.display_order
FROM event_detail_section_catalog section
JOIN event_publication publication ON publication.event_id = section.event_id
WHERE NOT EXISTS (
    SELECT 1 FROM event_detail_section_publication snapshot
    WHERE snapshot.event_id = section.event_id AND snapshot.section_id = section.id
);

CREATE TABLE IF NOT EXISTS event_notice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    content VARCHAR(1000) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_time TIMESTAMP NOT NULL,
    published_time TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS homepage_banner (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    organizer_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    subtitle VARCHAR(200) NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    city VARCHAR(80) NOT NULL,
    display_start_time TIMESTAMP NOT NULL,
    display_end_time TIMESTAMP NOT NULL,
    display_order INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL,
    created_time TIMESTAMP NOT NULL,
    updated_time TIMESTAMP NOT NULL,
    published_time TIMESTAMP NULL,
    CONSTRAINT uk_homepage_banner_event UNIQUE (event_id)
);

CREATE TABLE IF NOT EXISTS homepage_banner_publication (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    organizer_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    subtitle VARCHAR(200) NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    city VARCHAR(80) NOT NULL,
    display_start_time TIMESTAMP NOT NULL,
    display_end_time TIMESTAMP NOT NULL,
    display_order INT NOT NULL DEFAULT 0,
    published_time TIMESTAMP NOT NULL,
    CONSTRAINT uk_homepage_banner_publication_event UNIQUE (event_id)
);
