CREATE TABLE IF NOT EXISTS ticket_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    ticket_category_id BIGINT NOT NULL,
    unit_price_cents BIGINT NOT NULL DEFAULT 0,
    amount_cents BIGINT NOT NULL DEFAULT 0,
    active_grab_key VARCHAR(96) NULL,
    order_status VARCHAR(32) NOT NULL,
    created_time TIMESTAMP NOT NULL,
    pay_time TIMESTAMP NULL,
    cancel_time TIMESTAMP NULL,
    expire_time TIMESTAMP NOT NULL
);

ALTER TABLE ticket_order DROP CONSTRAINT IF EXISTS uk_ticket_order_once;
ALTER TABLE ticket_order ADD COLUMN IF NOT EXISTS unit_price_cents BIGINT NOT NULL DEFAULT 0;
ALTER TABLE ticket_order ADD COLUMN IF NOT EXISTS amount_cents BIGINT NOT NULL DEFAULT 0;
ALTER TABLE ticket_order ADD COLUMN IF NOT EXISTS active_grab_key VARCHAR(96) NULL;
UPDATE ticket_order
SET active_grab_key = CONCAT(user_id, ':', session_id, ':', ticket_category_id)
WHERE order_status <> 'CANCELED' AND active_grab_key IS NULL;
ALTER TABLE ticket_order ADD CONSTRAINT IF NOT EXISTS uk_ticket_order_active UNIQUE (active_grab_key);

CREATE TABLE IF NOT EXISTS electronic_ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    ticket_code VARCHAR(64) NOT NULL,
    ticket_status VARCHAR(32) NOT NULL,
    generated_time TIMESTAMP NOT NULL,
    verified_time TIMESTAMP NULL,
    verifier_id BIGINT NULL,
    CONSTRAINT uk_electronic_ticket_order UNIQUE (order_id),
    CONSTRAINT uk_electronic_ticket_code UNIQUE (ticket_code)
);

CREATE TABLE IF NOT EXISTS async_grab_request (
    request_id VARCHAR(64) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    ticket_category_id BIGINT NOT NULL,
    request_status VARCHAR(32) NOT NULL,
    order_id BIGINT NULL,
    error_message VARCHAR(255) NULL,
    created_time TIMESTAMP NOT NULL,
    updated_time TIMESTAMP NOT NULL
);
